assign_nfc_tag:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            integration: teddycloud
    file:
      required: true
      selector:
        file:
          accept: ".nfc"
